### ISSUE TITLE
`Structure of the Document` needs adjustment

### ISSUE THREAD

**Issue by zrgt** [admin-shell-io/aas-specs-aasx#13]
**Describe the bug**
Currently the `Structure of the Document` in [IDTA-01005_Introduction.adoc](https://github.com/admin-shell-io/aas-specs-aasx/blob/IDTA-01005-3-1_working/documentation/IDTA-01005/modules/ROOT/pages/IDTA-01005_Introduction.adoc ) still refers on numbered clauses, which is not the case anymore. Also the structure has been adjusted in c0ae8e26cab4bf3188a0a4f10a905dfbf9705880: `Introduction.adoc` includes now `Preamble`, `Introduction` and `Basic Concepts and Leading Picture`.

How should we proceed? Should we split `Introduction.adoc` to three docs and thus also clauses or should we adapt the text?

**Where**
https://github.com/admin-shell-io/aas-specs-aasx/blob/IDTA-01005-3-1_working/documentation/IDTA-01005/modules/ROOT/pages/IDTA-01005_Introduction.adoc)

**Comment by BirgitBoss** [comment]
The structure should be as in Part 1 (and the same in all parts). The text needs to be adopted to new structure.

**Comment by zrgt** [comment]
Fixed in #16
