### ISSUE TITLE
`Terms and definitions` are missing in the documentation

### ISSUE THREAD

**Issue by zrgt** [admin-shell-io/aas-specs-aasx#14]
**Describe the bug**
In c0ae8e26cab4bf3188a0a4f10a905dfbf9705880: the  `terms and definitions` part was removed. Was it on purpose?

If yes, we should adjust the text in the `Structure of the Document` in [IDTA-01005_Introduction.adoc](https://github.com/admin-shell-io/aas-specs-aasx/blob/IDTA-01005-3-1_working/documentation/IDTA-01005/modules/ROOT/pages/IDTA-01005_Introduction.adoc )

**Where**
https://github.com/admin-shell-io/aas-specs-aasx/blob/IDTA-01005-3-1_working/documentation/IDTA-01005/modules/ROOT/pages/IDTA-01005_Introduction.adoc)

**Comment by BirgitBoss** [comment]
No, this is not on purpose

The structure should be as in Part 1. The text needs to be adopted to new structure.

**Comment by zrgt** [comment]
Fixed in #16
