### ISSUE TITLE
[BUG] Clarify if relative paths are allowed

### ISSUE THREAD

**Issue by FrankSchnicke** [admin-shell-io/aas-specs-aasx#3]
During discussion of https://github.com/admin-shell-io/aasx-package-explorer/issues/654 with @BirgitBoss it popped up if relative URIs are allowed in the Relationship of the *.rels files. As of now, the OPC spec supports this and in the spec on p. 20 the following is written in Note 2:

`
The path within the .rels file of the Open Package Conventions container can be a relative or absolute Open Package Conventions path.
`

This should be clarified and, if relative paths are not allowed, the spec should be updated to reflect this fact.

**Comment by BirgitBoss** [comment]
relative path are allowed, the misunderstanding came from mixing folder structure with relationship path. See also #10

**Comment by BirgitBoss** [comment]
Proposal: add note
`Note 1: the internal relative paths shall be relative to the parent directory of the _rels folder (see ISO/IEC 29500-2).`
+ remove "/" from folder structure

**Comment by sebastiankb** [comment]
> remove "/" from folder structure

doing this, a total path would be not possible anymore, isn't it?

**Comment by BirgitBoss** [comment]
No, it just says that there is not requirements that is shall start with  a "/" but only files with relatives path are part of the aasx
